# Generated by Django 5.0.6 on 2024-06-02 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('faculty', models.CharField(choices=[('AIandML', 'ИИ и машинное обучение'), ('cybersecurity', 'Кибербезопасность'), ('networks', 'Сетевые технологии и коммуникации'), ('bioInformatics', 'Биоинформатика и медицинские IT'), ('VRandAR', 'Виртуальная и дополненная реальность'), ('quantInformatics', 'Квантовая информатика'), ('digitalArt', 'Цифровое искусство')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('theme', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='problems_media/')),
                ('faculty', models.CharField(blank=True, choices=[('AIandML', 'ИИ и машинное обучение'), ('cybersecurity', 'Кибербезопасность'), ('networks', 'Сетевые технологии и коммуникации'), ('bioInformatics', 'Биоинформатика и медицинские IT'), ('VRandAR', 'Виртуальная и дополненная реальность'), ('quantInformatics', 'Квантовая информатика'), ('digitalArt', 'Цифровое искусство')], max_length=100, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('students', models.ManyToManyField(blank=True, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('is_right', models.BooleanField(blank=True, default=False)),
                ('is_check', models.BooleanField(blank=True, default=False)),
                ('text', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='answers_media/')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.problem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.teacher'),
        ),
    ]
